<?php
// $Id $

/**
 * Implementation of hook_form_alter().
 */
function bryght_form_alter($form_id, &$form) {
  // Insert the CSS box into the theme settings page.
  if ($form_id == 'system_theme_settings') {
    $form['css'] = array(
      '#type' => 'fieldset',
      '#title' => t('Styles'),
      '#weight' => 0,
      '#attributes' => array('id' => 'bryght_css_form'),
    );
    $form['css'] += bryght_css_form(arg(4));
    $form['#submit']['bryght_css_form_submit'] = array();
    $form['theme'] = array('#type' => 'value', '#value' => arg(4));
  }

}

/**
 * Return the CSS box form array.
 */
function bryght_css_form($theme) {
  $form['custom_css'] = array(
    '#type' => 'textarea',
    '#rows' => 20,
    '#default_value' => variable_get('custom_css_'. $theme, ''),
    '#title' => t('Custom CSS'),
  );
  return $form;
}

function bryght_css_form_submit($form_id, $values) {
  $theme = $values['theme'];
  variable_set('custom_css_'. $theme, $values['custom_css']);
}

function bryght_menu($may_cache) {
  init_theme();
  global $theme_key;
  if (!$may_cache) {
    if ($css = variable_get('custom_css_'. $theme_key, '')) {
      drupal_set_html_head('<style type="text/css" media="all">'. $css .'</style>');
    }
  }
}