<?php

function favourites_page_menu($may_cache) {
  $items = array();
  global $user;
  if (!$may_cache) {
    if($user->uid != 0) {
      $items[] = array(
        'path' => 'user/'. arg(1) .'/favourites',
        'title' => t('Your Favourites'),
        'callback' => 'favourites_page_display',
        'access' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => 5
      );
    }
  }
  return $items;
}

function favourites_page_display() {
  global $user;
  if(arg(1) == $user->uid || user_access('administer users')) {
  drupal_set_title(t('YOUR FAVOURITES'));
  $node_types = node_get_types();
  $fav_list = '<div id="myfavourites">';
  $fav_list .= theme('favourites_intro');
  foreach($node_types as $type) {
    $items = array();
    if (variable_get(FAVORITE_NODES_NODE_TYPE . $type->type, 0)) {
      $favorites = favorite_nodes_get($user->uid, $type->type, variable_get(FAVORITE_NODES_BLOCK_LIMIT, 10));
      if (count($favorites) > 0) {
        foreach ($favorites as $favorite) {
          // gets topic
          $cats = taxonomy_node_get_terms($favorite->nid);
            foreach($cats as $cat) {
            if($cat->vid == 3) {
              $topic = $cat->name;
              break;
            }
          }
          // gets annotation
          $node = node_load($favorite->nid);
          $revisions = node_revision_list($node);
          foreach($revisions as $revision) {
            if($revision->current_vid != '') {
              $vid = $revision->current_vid;
              break;
            }
          }
          $annotation = db_result(db_query('SELECT field_annotations_value FROM content_type_daily_dose WHERE vid = %d', $vid));
          // themes it up
          $fav_list .= theme('favourites_page', $favorite, $node->created, $topic, $annotation);
        }
      }
    }
  }
  $fav_list .= '</div>';
  $no_fav = 'You have no favourites at this time.';
  $fav_list = ($fav_list == '<div id="myfavourites"></div>') ? $no_fav : $fav_list;
  print theme('page', $fav_list);
  }
  else {
    drupal_access_denied();
  }
}

function theme_favourites_page($favorites, $creation_date, $topic, $annotation) {
  $output = '<div class="afavourite">';
  $output .= '<span class="topic">'. $topic .'</span>';
  $output .= '<span class="date">'. strtoupper(date('l F j, Y', $creation_date)) .'</span>';
  $output .= '<h4>'. l($favorites->title, 'node/'. $favorites->nid) .'</h4>';
  $output .= '<p>'. $annotation .'</p>';
  $output .= '<span class="remove_favourite">'. l(t('remove'), 'favorite_nodes/delete/'. $favorites->nid) .'</span>';
  $output .= '</div>';
  return $output;
}

function theme_favourites_intro() {
  return (t("Keep all your favourite doses on hand for easy access."));
}
