<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Mon, 07/23/2007 - 20:35
 * View: Vitamin_V
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   Vitamin_V, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $created -- Display the post time of the node.
 * $created_label -- The assigned label for $created
 * $body -- Display the Main Content.
 * $body_label -- The assigned label for $body
 * $nid -- Display the NID of a node.
 * $nid_label -- The assigned label for $nid
 *
 * This function goes in your views-list-Vitamin_V.tpl.php file
 */
 
$city = vitamin_city_current_city();
$node = node_load($nid);
  ?>
<div class="daily-dose">
  <span class="date"><p><?php print format_date($node->created, 'custom', "F jS, Y") ?></p></span>

<h2 class="title"><?php print $title?></h2>

<div class="meta-block">
  <?php
    if (count($node->taxonomy)) {     
      $mytags = '';
      print '<div class="dose-links">';
      foreach($node->taxonomy as $term) {
        //Free tags
        if($term->vid == 1) {
          $mytags .= l($term->name, $city->field_city_url_path[0]['value'] .'/tag/'. $term->tid) .', ';
        }
        //Topic
        elseif($term->vid == 3) {
          $mytopic = $term->name;
        }
      }
      print '<h4>'. t($mytopic) .'</h4>';

      print '<h5>'. t('MAKE IT YOURS') . '</h5>';
      print '<div class="links"><ul>';
      print '<li>'. l(t('SEND TO A FRIEND'), 'forward', array('title' => 'Forward this page to a friend', 'class' => 'forward-page'), 'path=node/'. $nid) .'</li>';
      if($node->field_map_link[0]['url'] != '') {
        print '<li>'. l(t('ADD TO FAVORITES'), 'favorite_nodes/add/'. $nid) .'</li>';
        print '<li class="last">'. l(t('GOOGLE MAP'), $node->field_map_link[0]['url']) .'</li>';
      }
      else {
        print '<li class="last">'. l(t('ADD TO FAVORITES'), 'favorite_nodes/add/'. $nid) .'</li>';
      }
      print '</ul></div>';

      $related_doses = related_nodes_display_related($node->nid);
      if ($related_doses) {
        print '<h5>' . t('RELATED DOSES') . '</h5>';
        print '<div class="links">';
        print $related_doses;
        print '</div>';
      }

      if($mytags != '') {
        print '<h5>' . t('TAGS') . '</h5>';
        print '<p>'. substr($mytags, 0, -2) .'</p>';
      }
      print '</div>';
    }
  ?>
</div> <!-- /meta-block -->
<div class="view-field view-data-body"><?php print $node->body?></div>

<div class="thesocial">
	<ul>
		<li id="tweet-<?php $node->nid ?>" class="tweetthis"><a href="<?php echo url("node/{$node->nid}", NULL, NULL, true) ?>">Tweet this</a></li>
		<li class="fblike"><fb:like href="<?php echo url("node/{$node->nid}", NULL, NULL, true) ?>" layout="button_count" show_faces="false"></fb:like></li>
	</ul>
</div>


<?php
global $user;
$notadmin = (in_array('Site Admin', $user->roles)) ? FALSE : TRUE;

if($ad === TRUE && $notadmin === TRUE) {
  vitamin_city_display_ad('ad_inline_300x250_home');
}
?>

</div>
