<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Fri, 08/24/2007 - 11:14
 * View: Top10_vancouver_1
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   Top10_vancouver_1, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $created -- Display the post time of the node.
 * $created_label -- The assigned label for $created
 * $field_annotations_value -- 
 * $field_annotations_value_label -- The assigned label for $field_annotations_value
 *
 * This function goes in your views-list-Top10_vancouver_1.tpl.php file
 */

?>

<div class="top-10-container">

<div class="taxonomy-right">
  <?php print $name?>
</div>

<div class="top10-title">
  <?php print $term_node_5_name?>
</div>

<div class="view-field view-top10-date">
  <?php print $created ?>
</div>

<div class="view-field view-top10-title">
  <?php print $title?>
</div>

<div class="view-field view-topten-annotation">
  <?php print $field_annotations_value?>
</div>

</div>
